version: '3.8'

services:
  # PostgreSQL数据库 (生产环境使用云数据库)
  postgres:
    image: postgres:15-alpine
    container_name: guoxue_postgres_prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guoxue}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - guoxue_network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Redis缓存 (生产环境使用云Redis)
  redis:
    image: redis:7-alpine
    container_name: guoxue_redis_prod
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - guoxue_network
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # 后端服务 (生产环境扩展)
  backend:
    build:
      context: ./backend
    container_name: guoxue_backend_prod
    restart: always
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-guoxue}
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_DB_URL=http://chroma:8000
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      - postgres
      - redis
      - chroma
      - minio
    volumes:
      - ./backend:/app
    networks:
      - guoxue_network
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Nginx负载均衡
  nginx:
    image: nginx:alpine
    container_name: guoxue_nginx_prod
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - guoxue_network
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  guoxue_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: